version: '3.8'

services:
  web:
    image: nginx:1.21-alpine
    container_name: classroom-web
    working_dir: /application
    volumes:
      - ./environment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    networks:
      - classroom
    ports:
      - ${EXTERNAL_WEBSERVER_PORT}:80
    restart: unless-stopped

  php:
    build:
      context: environment/php
      dockerfile: Dockerfile
      args:
        XDEBUG_HOST: ${XDEBUG_HOST}
        XDEBUG_PORT: ${XDEBUG_PORT}
        XDEBUG_INSTALL: ${XDEBUG_INSTALL}
        XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST}
        XDEBUG_MODE: ${XDEBUG_MODE}
        XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL}
    container_name: classroom-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
    networks:
      - classroom
    restart: unless-stopped

  database:
    image: mysql:8.0.25
    container_name: classroom-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - classroom
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: classroom-mailhog
    ports:
      - ${MAIL_PORT}:1025
      - ${MAILHOG_DASHBOARD_PORT}:8025
    networks:
      - classroom
    restart: unless-stopped

networks:
  classroom:
    driver: bridge

volumes:
  data:
    name: mysql-data
